#!/usr/bin/env python3
"""Build hskExamples.js — a curated example-sentence lookup for the HSK app.

Reads the Roxaleen hsk-annotated-corpus sentence collection (Tatoeba /
Wiktionary / Kaikki / Leipzig) and, for every word present in the app's
vocabulary, picks ONE natural example sentence that is tagged with that word
plus its English translation.

Usage:
    build_hsk_examples.py <sentences.json> <hskWords.js> <hskExamples.js>

    - sentences.json: Roxaleen/hsk-annotated-corpus export/json/sentences.json
                      (git-LFS file; download via the media.githubusercontent
                      LFS endpoint before running).
    - hskWords.js:    the app's existing generated vocabulary (constrains the
                      example set to words the app actually uses).
    - hskExamples.js: JS output, keyed by hanzi.

The output is NOT embedded in each card — it stays a separate lookup map so the
2.8 MB vocabulary file is never regenerated by hand. The runtime code resolves
an example as: card.exampleHanzi (user-created custom words) OR HSK_EXAMPLES[hanzi].
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path


def to_pinyin(text: str) -> str:
    """Tone-marked pinyin for a sentence, computed at build time with pypinyin
    so the browser doesn't need a pinyin library at runtime."""
    try:
        from pypinyin import Style, lazy_pinyin
    except ImportError:
        return ""
    out = " ".join(lazy_pinyin(text, style=Style.TONE))
    # Don't leave a stray space before CJK punctuation ("nà 。" -> "nà。").
    return re.sub(r"\s+([，。？！、；：\"\"''（）])", r"\1", out)


def source_rank(source: str | None) -> int:
    """Tatoeba is the most natural learner-sentence source; prefer it."""
    return 0 if source == "tatoeba" else 1


def length_penalty(n: int) -> int:
    """Prefer a digestible sentence (~10-20 hanzi)."""
    if n < 5:
        return 40          # too fragmentary ("水。")
    if n > 30:
        return 15 + (n - 30) * 2
    if n > 22:
        return 6
    return 0


def example_score(sentence: dict, target: str) -> int:
    text = sentence["sentence"]
    score = source_rank(sentence.get("source")) * 10000
    score += length_penalty(len(text))
    # Bias toward easier sentences when a word has candidates of varying level.
    score += sentence.get("level") or 0
    return score


def parse_deck_hanzi(hsk_words_path: Path) -> set[str]:
    src = hsk_words_path.read_text(encoding="utf-8")
    start = src.index("export const HSK_WORDS = ") + len("export const HSK_WORDS = ")
    end = src.index(";\n\nexport const HSK_CLASSIC_LEVELS")
    deck = json.loads(src[start:end].strip())
    return {c["hanzi"] for c in deck}


def build_examples(sentences_path: Path, wanted: set[str]) -> dict[str, dict]:
    corpus = json.loads(sentences_path.read_text(encoding="utf-8"))

    by_word: dict[str, list[dict]] = {}
    for text, meta in corpus.items():
        if not meta.get("translation"):
            continue
        for word, _pos in meta.get("tags", []):
            if word in wanted:
                by_word.setdefault(word, []).append(
                    {"sentence": text, "translation": meta["translation"],
                     "source": meta.get("source"), "level": meta.get("level")}
                )

    examples: dict[str, dict] = {}
    for word, candidates in by_word.items():
        best = min(candidates, key=lambda c: example_score(c, word))
        examples[word] = {
            "hanzi": best["sentence"],
            "pinyin": to_pinyin(best["sentence"]),
            "english": best["translation"].strip(),
        }
    return examples


def write_js(examples: dict[str, dict], output_path: Path) -> None:
    with output_path.open("w", encoding="utf-8") as f:
        f.write("// HSK example sentences — usage lookup, keyed by hanzi.\n")
        f.write("// One natural example sentence + English translation per word.\n")
        f.write("// Built from Roxaleen/hsk-annotated-corpus (Tatoeba CC BY 2.0 FR,\n")
        f.write("// Wiktionary via Kaikki, Leipzig Corpora Collection).\n")
        f.write("// Generated by scripts/build_hsk_examples.py — do not edit by hand.\n\n")
        f.write("export const HSK_EXAMPLES = ")
        json.dump(examples, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    print(f"Words with examples: {len(examples)}")


def main() -> int:
    if len(sys.argv) != 4:
        print("usage: build_hsk_examples.py <sentences.json> <hskWords.js> <hskExamples.js>",
              file=sys.stderr)
        return 2
    wanted = parse_deck_hanzi(Path(sys.argv[2]))
    examples = build_examples(Path(sys.argv[1]), wanted)
    write_js(examples, Path(sys.argv[3]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())